# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running


In [ ]:
np.__version__

'1.19.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])


In [ ]:
np.array([0.8,0.6,0.4])

array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements, 
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 1.21098623, 0.28192741])


In [80]:
def randomArray():
  return 0.75 * np.random.random_sample(10) + 0.25

randomArray()

array([0.28487094, 0.32663586, 0.46503406, 0.79376953, 0.53384397,
       0.8321419 , 0.74808415, 0.45788612, 0.90555755, 0.87315625])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here


np.empty permet de créer un tableau en renseignant en paramètre les dimensions et le type d'objet souhaité

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can chose the length of this array.


In [ ]:
np.zeros([2,2], dtype = int)


array([[0, 0],
       [0, 0]])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
arrMission6 = np.empty([10], dtype = int)
print(arrMission6)

[4599432917879275592 4601261925719202037 4606182987044053486
 4605347829778699454 4601712106178888214 4603528224104025273
 4605281812945681496 4598286638073835909 4601807544692947768
 4601231360323692715]


In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.


In [77]:
np.random.randint(0,8,50,dtype=int)

array([6, 1, 5, 7, 5, 0, 6, 2, 7, 1, 6, 3, 2, 4, 0, 6, 2, 2, 6, 3, 1, 1,
       7, 5, 3, 5, 0, 6, 1, 6, 7, 0, 2, 3, 3, 7, 1, 2, 6, 1, 6, 0, 5, 7,
       5, 0, 6, 5, 7, 2])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6


In [ ]:
arrMission6[3:7]

array([4605347829778699454, 4601712106178888214, 4603528224104025273,
       4605281812945681496])

In [ ]:
# Mission 9 : Use the `argmin()` method to return the index of the smallest element in the array from mission 6
arrMission6.argmin()

7

In [ ]:
# Mission 10 : Using the `where()` method, return the indices of all the values in the array from mission 6 that are greater than their median value.
np.where(arrMission6 > np.median(arrMission6))

(array([2, 3, 5, 6, 8]),)

In [ ]:
# Mission 11: Create 3 arrays filled with 5 random integers each, and place them in another array.
# You have now an array with (3, 5) shape. You can use the `shape` attribute to check it.
# Display the elements, with each column appearing on a different line (so there will be 5 lines with 3 values each)


In [ ]:
arr1= np.random.randint(10, size=5)
arr2= np.random.randint(10, size=5)
arr3= np.random.randint(10, size=5)


In [ ]:
arrTot = np.vstack((arr1,arr2,arr3))
print(arrTot)

[[2 8 5 9 2]
 [9 9 3 3 7]
 [4 0 8 8 5]]


In [ ]:
np.transpose(arrTot)

array([[2, 9, 4],
       [8, 9, 0],
       [5, 3, 8],
       [9, 3, 8],
       [2, 7, 5]])

In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that returns the smallest and largest value it contains, with their indices!
# You are allowed to use `min()` and `max()` methods.
# Example with a shorter array: [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Example with a shorter array: [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)


In [ ]:
arrMission12 = np.empty(20)
print(arrMission12)

[0.17094531 0.52093092 0.28095399 0.3528048  0.97887991 0.38832547
 0.63561426 0.94103082 0.930723   0.9589352  0.45306013 0.75061903
 0.07878543 0.90887593 0.10153302 0.91440721 0.59951889 0.2595551
 0.01442365 0.79544094]


In [79]:
def mini_maxi(arr):
  mini =(arr.min(), arr.argmin())
  maxi = (arr.max(), arr.argmax())
  return mini, maxi

mini_maxi(arrMission12)

((0.014423645456173695, 18), (0.9788799117402796, 4))

In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Create a function that will go through each array using a for loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return all indices where the values of the 2 arrays happen to be equal, in a list.
# If no values are equal at the same indices across the 2 arrays, that list will be empty.
# Example with shorter arrays: [1, 3, 5, 7] & [2, 3, 5, 8] -> [1, 2]
# Example with shorter arrays: [1, 1, 1, 1] & [1, 2, 3, 4] -> [0]


In [ ]:
arrA= np.random.randint(0, 10, size=20)
arrB= np.random.randint(0, 10, size=20)
print ('arrA=', arrA)
print ('arrB=', arrB)

arrA= [2 1 2 7 8 4 1 1 2 8 7 3 0 0 2 4 1 1 4 5]
arrB= [4 7 6 8 4 0 5 8 9 3 0 5 0 7 4 7 4 9 1 2]


In [76]:
def listeEquals(arrA, arrB):
  listeAB = []
  for i in range(20):
    if arrA[i] == arrB[i]:
      listeAB.append(i)
  return listeAB

listeEquals(arrA, arrB)

[12]

In [ ]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2

In [ ]:
arrA == arrB

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False])