In [1]:
import numpy as np

# Mission 1

Find a way to calculate the following statistical indicators for any given one-dimensional array using NumPy functions, and use them on a array filled with 20 random floats.
- mode
- median
- average
- the range (the difference between max and min)
- standard deviation
- variance
- the different quantiles

Then, create another array with 20 random floats and calculate the Pearson coefficient between the two arrays.

In [3]:
arr1 = np.random.rand(20)
print(arr1)

[0.20307251 0.72786583 0.77721783 0.60413246 0.24302954 0.41061353
 0.27959745 0.26329458 0.2697208  0.876358   0.37271208 0.78495745
 0.19995105 0.66368499 0.19802327 0.7604903  0.30446918 0.74058004
 0.51039243 0.04705766]


In [11]:
#mode
values, counts = np.unique(arr1, return_counts=True)
index = np.where(max(counts))
values[index]

array([0.04705766])

In [16]:
#median
np.median(arr1)

0.39166280087454985

In [14]:
#average
arr1.mean()

0.4618610484038207

In [18]:
#range
range = max(arr1)-min(arr1)
range

0.8293003379333973

In [19]:
#standard deviation
np.std(arr1)

0.24966386509657568

In [ ]:
#variance
np.var(arr1)

In [62]:
#quantiles
q1 = np.quantile(arr1, 0.25)
q2 = np.quantile(arr1, 0.5)
q3 = np.quantile(arr1, 0.75)
print (q1,q2,q3)

0.25822831732011653 0.39166280087454985 0.7310443812544811


In [24]:
arr2 = np.random.rand(20)
print(arr2)

[0.6086188  0.27262649 0.16518056 0.46309985 0.81573869 0.11601751
 0.08117837 0.79005106 0.22739926 0.82874829 0.37434539 0.07082668
 0.46760003 0.02510593 0.50919362 0.19856411 0.60231185 0.26300915
 0.92268801 0.48508128]


In [26]:
#Pearson coefficient
np.corrcoef(arr1,arr2)

array([[ 1.        , -0.29731889],
       [-0.29731889,  1.        ]])

## Mission 2

Create a function using NumPy that indicates the values (integers only), from -100 to 100, where the remainder from performing Euclidean division by both 3 and 7 is equal.

In [43]:
def getValue():
 arr = np.arange(-100,101,1,dtype=int)
 result = []
 for value in arr:
   if value%7 == value%3:
     result.append(value)
 return result

getValue()

[-84,
 -83,
 -82,
 -63,
 -62,
 -61,
 -42,
 -41,
 -40,
 -21,
 -20,
 -19,
 0,
 1,
 2,
 21,
 22,
 23,
 42,
 43,
 44,
 63,
 64,
 65,
 84,
 85,
 86]

## Mission 3

Create a function that returns the [inverse value (for `3`, return `1/3`)](https://en.wikipedia.org/wiki/Multiplicative_inverse) of a set of values contained in a NumPy array

In [60]:
def inverse(arr, set_start,set_stop):
  for value in arr:
    index = np.where(arr == value)
    arr[index] = 1/value
  return arr[set_start : set_stop]

arrTest = np.arange(1,10, dtype=float)
inverse(arrTest, 5, 9)

array([0.16666667, 0.14285714, 0.125     , 0.11111111])