In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
import random

In [3]:

# constructeur numpy
my_tableau=np.array([1,2,3])
print(" my_tableau: ", my_tableau)
my_tableau.shape

#  taille d'un tableau
import numpy as np
tableau=np.array([1,2,3])
tableau.shape
print("mon tableau: ", tableau)
print(tableau.size)
#  faire un tableau de 0 avec 3 lignes et 2 colonnes
tableau2=np.zeros((3,2))
tableau2.shape
print("mon tableau2: ", tableau2)
#  faire un tableau de 1 avec 3 lignes et 2 colonnes
tableau3=np.ones((3,2))
tableau3.shape
print("mon tableau3: ", tableau3)

#  faire un tableau de 7 avec 3 lignes et 2 colonnes
tableau4=np.full((3,2),7)
tableau4.shape
print("mon tableau4: ", tableau4)

#  faire un tableau de 0 ou 1 avec 4 lignes et 4 colonnes
tableau44=np.eye(4)
tableau44.shape
print("mon tableau44: ", tableau44)

# faire un tableau de valeurs aleatoire de 3 lignes et 4 colonnes
# reparties selon la loi normale centrée en zero donc utlisation
#  de la distribution normale
tableau5=np.random.randn(3,4)
tableau5.shape
print("mon tableau5: ", tableau5)
# pour fixer le generateur afin d'avoir toujours le meme aleatoire on utilise seed, on voit que les valeurs aléatoires sont fixées
# np.random.seed(0)
tableau5=np.random.randn(3,4)
tableau5.shape
print("mon tableau5: ", tableau5)
# on peut aussi fixer les aléatoires à une autre valeur
# np.random.seed(4544454)

# pour avoir un tableau de 20 points répartis de maniére équitable entre 0 et 10
# np.linspace(0,10,20)
tableau6=np.linspace(0,10,20)
tableau6.shape
print("mon variable tableau6 : ", tableau6)
# arange permet d'avoir un tableau avec un pas. Ici des valeurs de 0 à 10 avec un pas de 0.1

tableau7=np.arange(0,10,0.1)
tableau7.shape
print("mon variable tableau7: ", tableau7)

# choix du nombre de byte des variables de 16 à 128 il faut rajouter dtytpe=np.float64 influence la vitesse de traitement du programme

tableau8=np.linspace(0,10,20, dtype=np.float64)
tableau8.shape
print("mon variable tableau8 : ", tableau8)

tableau88=np.linspace(0,10,20, dtype=np.float16)
tableau88.shape
print("mon variable tableau88 : ", tableau88)

####################################
# MANIPULATION DES TABLEAUX

####################################
####################################
####################################

 my_tableau:  [1 2 3]
mon tableau:  [1 2 3]
3
mon tableau2:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
mon tableau3:  [[1. 1.]
 [1. 1.]
 [1. 1.]]
mon tableau4:  [[7 7]
 [7 7]
 [7 7]]
mon tableau44:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
mon tableau5:  [[-1.80149344  0.33930869  0.49070163 -0.56639717]
 [ 0.64948147 -0.12209004  1.68037062 -0.16401704]
 [ 1.85435191 -0.56209659 -0.82261563  0.71094909]]
mon tableau5:  [[ 1.15483949  0.97944189 -0.64563345  0.44423002]
 [ 1.01640103 -0.758861   -0.55795719  0.47722151]
 [ 0.39048958  1.86447606  1.2136078   1.92671514]]
mon variable tableau6 :  [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
mon variable tableau7:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 

In [9]:
import pandas as pd
import requests
import json


In [10]:
requests.get("http://127.0.0.1:5000/").text

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B9ECB82030>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))

In [ ]:
data=json.loads(requests.get("http://127.0.0.1:5000/").text)




In [ ]:
pd.DataFrame(data).value_counts()


localidsation  prenoms   salire  typeDePoste
france         Paul      4000    CDD            4
                         6000    CDI            4
canada         Caroline  2000    freelance      3
               Michel    6000    CDD            3
               Paul      3000    CDI            3
                                               ..
france         Fabrice   2000    CDI            1
                         3000    CDI            1
                         4000    CDD            1
                                 CDI            1
thailande      Yvna      6000    freelance      1
Name: count, Length: 205, dtype: int64

In [6]:
pd.DataFrame(data).prenoms.value_counts()

NameError: name 'data' is not defined