# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
np.__version__


'1.23.5'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])

my_array=np.array([0.8, 0.6, 0.4])
print(my_array)
# autre solution avec la fonction range par valeurs croissantes et pas de 0.2
# avec [::-1] pour inverser l'ordre
my_array2=np.arange(0.4,1.0,0.2)[::-1]
print(my_array2)
# autre solution par veleur décroissantes
my_array3=np.arange(0.8,0.3,-0.2)
print(my_array3)
print(my_array3.shape)

[0.8 0.6 0.4]
[0.8 0.6 0.4]
[0.8 0.6 0.4]
(3,)


In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])
import random
np.random.seed(0)  # pour avoir toujours la même valeur
my_array = np.random.uniform(0.25, 1.0, 10)
print(my_array)

[0.66161013 0.78639202 0.70207253 0.65866239 0.5677411  0.73442058
 0.57819041 0.91882975 0.97274707 0.53758114]


In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
# il crée une structure de tableau vide, du moins sans type
my_array=np.empty((2,2), dtype=np.int64) # exemple d'une matrice 2*2 avec des valeur de type int sur 64 bits
print(my_array)
my_array.shape

[[4605380978949069210 4603579539098121012]
 [4600877379321698716 4596373779694328224]]


(2, 2)

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
my_array=np.zeros((5,2))
print(my_array)
my_array.shape

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


(5, 2)

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
import random
np.random.seed(80)  # pour avoir toujours la même valeur
my_array = np.random.randint(1,10,size=10)
print(my_array)
my_array.shape

[7 4 3 4 7 8 8 4 2 6]


(10,)

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
import random
np.random.seed(100)  # pour avoir toujours la même valeur

my_array = np.random.choice([0, 1, 2, 3, 4, 5, 6, 7], size=50) # solution avec le .choice  on peut aussi remplacer le tableau par my_array3
print(my_array)
my_array.shape
# solution avec le .choice  en integrant le tableau  my_array4 à la place du tableau
my_array4 = np.arange(0,8,step=1)
my_array3 = np.random.choice(my_array4, size=50)
print(my_array3)
my_array3.shape
# autre solution avec le .uniform
my_array2 = np.random.uniform(low=0, high=8, size=50).astype(int)
print(my_array2)
my_array2.shape


[0 0 3 7 7 7 0 2 6 4 2 5 2 2 6 2 1 0 0 7 4 3 4 2 0 3 1 5 6 2 3 4 4 7 1 5 5
 3 4 4 3 3 3 7 1 7 1 5 6 7]
[7 3 0 2 1 1 6 3 2 7 5 3 0 6 1 6 0 7 7 5 6 4 2 0 0 2 5 2 1 0 5 2 6 1 5 4 2
 0 3 3 3 5 6 0 5 1 4 2 3 6]
[7 7 2 4 2 2 1 1 0 4 3 4 5 1 7 7 4 3 2 1 2 1 1 7 7 4 5 2 0 3 4 0 4 7 3 2 6
 6 2 5 4 2 0 2 3 5 2 5 1 5]


(50,)